import { readFile } from 'node:fs/promises';
import path from 'node:path';
import ReactSwagger from './react-swagger';

const SPEC_PATH = path.join(process.cwd(), 'docs', 'swagger.json');

// /api-docs — renders the OpenAPI spec generated by scripts/generateSwagger.js
// (docs/swagger.json) as an interactive Swagger UI page. That file regenerates
// on every `npm run build` (via the `prebuild` script) and can be regenerated
// manually with `npm run swagger`. The raw JSON is also served as-is at
// /api/docs for external tools.
async function getApiDocs() {
  try {
    const raw = await readFile(SPEC_PATH, 'utf-8');
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

export const metadata = {
  title: 'API Docs — Cremen Smart Spaces'
};

export default async function ApiDocsPage() {
  const spec = await getApiDocs();

  if (!spec) {
    return (
      <section style={{ padding: '2rem', fontFamily: 'sans-serif' }}>
        <h1>API docs not generated yet</h1>
        <p>
          Run <code>npm run swagger</code> to generate <code>docs/swagger.json</code>, then reload this page.
        </p>
      </section>
    );
  }

  return <ReactSwagger spec={spec} />;
}
